const ji = [
	{
		constant: false,
		inputs: [{ name: 'name', type: 'string' }],
		name: 'setNick',
		outputs: [],
		payable: true,
		stateMutability: 'payable',
		type: 'function',
	},
	{
		constant: false,
		inputs: [
			{ name: 'id', type: 'uint256' },
			{ name: 'verdict', type: 'bool' },
		],
		name: 'resolveWord',
		outputs: [],
		payable: false,
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		constant: false,
		inputs: [{ name: 'text', type: 'string' }],
		name: 'addWord',
		outputs: [],
		payable: true,
		stateMutability: 'payable',
		type: 'function',
	},
	{
		constant: true,
		inputs: [{ name: '', type: 'address' }],
		name: 'names',
		outputs: [{ name: '', type: 'string' }],
		payable: false,
		stateMutability: 'view',
		type: 'function',
	},
	{
		constant: true,
		inputs: [],
		name: 'getContractBalance',
		outputs: [{ name: '', type: 'uint256' }],
		payable: false,
		stateMutability: 'view',
		type: 'function',
	},
	{
		constant: true,
		inputs: [{ name: '', type: 'uint256' }],
		name: 'words',
		outputs: [
			{ name: 'text', type: 'string' },
			{ name: 'bet', type: 'uint256' },
			{ name: 'owner', type: 'address' },
			{ name: 'resolved', type: 'bool' },
			{ name: 'verdict', type: 'bool' },
		],
		payable: false,
		stateMutability: 'view',
		type: 'function',
	},
	{
		constant: true,
		inputs: [],
		name: 'getTotalWords',
		outputs: [{ name: '', type: 'uint256' }],
		payable: false,
		stateMutability: 'view',
		type: 'function',
	},
	{
		constant: true,
		inputs: [{ name: 'ad', type: 'address' }],
		name: 'getNickByAddress',
		outputs: [{ name: '', type: 'string' }],
		payable: false,
		stateMutability: 'view',
		type: 'function',
	},
	{
		constant: true,
		inputs: [{ name: 'id', type: 'uint256' }],
		name: 'getWordById',
		outputs: [
			{ name: '', type: 'string' },
			{ name: '', type: 'address' },
			{ name: '', type: 'uint256' },
			{ name: '', type: 'bool' },
			{ name: '', type: 'bool' },
		],
		payable: false,
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ name: 'treasure_', type: 'address' }],
		payable: false,
		stateMutability: 'nonpayable',
		type: 'constructor',
	},
]

const address = '0x106dBbEd89cbd4E0da121286ac53A3A9aE2853fb'

module.exports = { abi: ji, address }
