const ji = [
	{
		inputs: [{ internalType: 'address payable', name: 'treasure_', type: 'address' }],
		stateMutability: 'nonpayable',
		type: 'constructor',
		signature: 'constructor',
	},
	{
		inputs: [{ internalType: 'string', name: 'text', type: 'string' }],
		name: 'addWord',
		outputs: [],
		stateMutability: 'payable',
		type: 'function',
		payable: true,
		signature: '0x4974da81',
	},
	{
		inputs: [],
		name: 'getContractBalance',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
		constant: true,
		signature: '0x6f9fb98a',
	},
	{
		inputs: [{ internalType: 'address', name: 'ad', type: 'address' }],
		name: 'getNickByAddress',
		outputs: [{ internalType: 'string', name: '', type: 'string' }],
		stateMutability: 'view',
		type: 'function',
		constant: true,
		signature: '0xe737c252',
	},
	{
		inputs: [],
		name: 'getTotalWords',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
		constant: true,
		signature: '0xc93194fe',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
		name: 'getWordById',
		outputs: [
			{ internalType: 'string', name: '', type: 'string' },
			{ internalType: 'address', name: '', type: 'address' },
			{ internalType: 'uint256', name: '', type: 'uint256' },
			{ internalType: 'bool', name: '', type: 'bool' },
			{ internalType: 'bool', name: '', type: 'bool' },
		],
		stateMutability: 'view',
		type: 'function',
		constant: true,
		signature: '0xed8868fb',
	},
	{
		inputs: [{ internalType: 'address', name: '', type: 'address' }],
		name: 'names',
		outputs: [{ internalType: 'string', name: '', type: 'string' }],
		stateMutability: 'view',
		type: 'function',
		constant: true,
		signature: '0x5cf3d346',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: 'id', type: 'uint256' },
			{ internalType: 'bool', name: 'verdict', type: 'bool' },
		],
		name: 'resolveWord',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
		signature: '0x211daad6',
	},
	{
		inputs: [{ internalType: 'string', name: 'name', type: 'string' }],
		name: 'setNick',
		outputs: [],
		stateMutability: 'payable',
		type: 'function',
		payable: true,
		signature: '0x20e98bf4',
	},
	{
		inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		name: 'words',
		outputs: [
			{ internalType: 'string', name: 'text', type: 'string' },
			{ internalType: 'uint256', name: 'bet', type: 'uint256' },
			{ internalType: 'address', name: 'owner', type: 'address' },
			{ internalType: 'bool', name: 'resolved', type: 'bool' },
			{ internalType: 'bool', name: 'verdict', type: 'bool' },
		],
		stateMutability: 'view',
		type: 'function',
		constant: true,
		signature: '0x884fc838',
	},
]

const address = '0x2046E6BD49f0692DDD238f1b10D7Da5db56C2cB6'

module.exports = { abi: ji, address }
